apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpt
spec:
  selector:
    matchLabels:
      app: kustomize
  template:
    metadata:
      labels:
        app: kustomize
    spec:
      containers:
      - name: demo
        image: kustomize:demo
