apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomizatio

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service 
      name: wpt 
      apiVersion: v1 
    fieldref:
      fieldpath: metadata.name