apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/MICRO

patchesStrategicMerge:
- container-env.yaml
#- custom-env.yaml
- volume.yaml
- replicate-and-rollout-strategy.yaml
- service-nodeport.yaml

images:
  - name: kustomize
    newName: test
    newTag: test
commonLabels:
  micro: kustomize

namespace: kustomize

nameSuffix: -kustomization-pre
