apiVersion: v1
kind: Service 
metadata:
  name: wpt
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30000
  selector:
    app: kustomize
