apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wpt
spec:
  template:
    spec:
      containers:
      - name: demo
        volumeMounts:
        - mountPath: /data/log
          name: api-volume
      volumes:
      - hostPath:
          path: /data/log/demo
          type: DirectoryOrCreate
        name: api-volume